### ISSUE TITLE
一部のフォントの両側が欠けます

### ISSUE THREAD

**Issue by nopnop2002** [nemuisan/WFONTX64#1]
こんにちは。
日本語で失礼します。
まずは、たいへん有益なツールの公開、ありがとうございます。

さて、以下の内容でYuGothic32.FNTを作成しました。

![YuGothic32](https://github.com/user-attachments/assets/1d903f9f-25c5-48ee-8668-c4b9a9edbf08)

YuGothic32.FNTのフォントを一覧で表示したところ、%、@、M、Wなどの一部のフォントの両側が欠けていることに気が付きました。

![IMG_5594](https://github.com/user-attachments/assets/3e7b60f8-48da-4400-b56c-3a0a4bcfb6d7)

FONTXエディターでも確認しましたがやはりフォントの両側が欠けています。

![YuGothic32-1](https://github.com/user-attachments/assets/08c79782-d04f-4bcb-8639-503367a74419)
![YuGothic32-2](https://github.com/user-attachments/assets/220af6fb-eea1-465e-ab2d-e6e93b383984)

以上、ご報告させていただきます。

**Comment by nemuisan** [comment]
nopnop2002様こんにちは、ねむいです。

選択されたYu Gothic UI はプロポーショナルフォントで半角英数字において文字により文字幅が大きく変化します。
プロポーショナルフォントを選択して変換した場合、半角を指定して想定されたピクセルサイズを
逸脱したサイズの文字がいくつか存在するためこのような現象になります。
これはオリジナルのWFONTX.exeからの仕様となります。

FONTX2ファイル変換の際は等幅フォント(BIZ UD ゴシックなど)のご使用をお勧めいたしします。

また、V1.20でプロポーショナルフォントを選択して変換した際にワーニングを
表示するように(+細かい修正を追加)しましたのでこちらをご使用をおねがいいたします。
[https://github.com/nemuisan/WFONTX64/releases/tag/FONTX2](https://github.com/nemuisan/WFONTX64/releases/tag/FONTX2)

**Comment by nopnop2002** [comment]
ねむい様、素早いご対応ありがとうございます。

>V1.20でプロポーショナルフォントを選択して変換した際にワーニングを

動作確認しました。
ありがとうございます。
